### PR TITLE
Support dynamic selection topic & partition

### PR DESCRIPTION
**Pull request by hailin0**
Support dynamic selection topic & partition

https://github.com/streamnative/pulsar-beat-output/issues/19
https://github.com/streamnative/pulsar-beat-output/issues/64

### CODE REVIEW

**Comment by hailin0** [comment]
@zhongxp1219 
@tyluffy 
@sijie 

Please help to review

**Comment by hailin0** [comment]
image
image

**Comment by hezhangjian** [comment]
@hailin0 Thanks for your contribution. It looks good. I have a concern, when will the producer getting prune?
If the user selects a key field that varies greatly, is there a risk of memory leak? Could you please explain more? thanks! :)

**Comment by hailin0** [comment]
> 

@Shoothzj 

I use another solution in my company: lru-cache 
I don't know if open source needs it

image

**Comment by hailin0** [comment]
> @hailin0 Thanks for your contribution. It looks good. I have a concern, when will the producer getting prune? If the user selects a key field that varies greatly, is there a risk of memory leak? Could you please explain more? thanks! :)


@Shoothzj

Use lru cache for dynamic producers

**Comment by zhongxp1219** [comment]
great job, i think it is useful for beats to collect logs and metrics and so on.

**Review by hezhangjian — APPROVED** [review]

**Comment by hezhangjian** [comment]
LGTM @tuteng

**Review by zhongxp1219 — APPROVED** [review]

**Comment by hezhangjian** [comment]
ping @tuteng

**Pull request merged**
