### PR TITLE
Support native go client

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation
pulsar-beat-output upgrade to native go client. pulsar-beat-output currently relies on cgo client, which is very complicated to install. so this pr is replaced by native go client.

### Modifications
Upgrade plan
1. Use go mod as the package manager.
Go mod is simple to use and is also officially recommended. However, there was a dependency problem during the test.
At present, package a depends on package b, package c depends on package b, but package c has modified package b, so there will be problems when using common package b, and no solution has been found for the time being.
2. Use glide as the package manager.
Glide guarantees that all dependencies will be placed under the vendor folder, which will result in a larger package, but can solve the above dependency problem.
Therefore, glide continues to be used as the package manager.

To solve the conflict problem of zstd, the following files have been modified:

```
pulsar-beat-output/vendor/github.com/apache/pulsar-client-go/pkg/compression/compression.go
pulsar-beat-output/vendor/github.com/apache/pulsar-client-go/pkg/compression/compression_test.go
pulsar-beat-output/vendor/github.com/apache/pulsar-client-go/pkg/compression/zstd.go
pulsar-beat-output/vendor/github.com/apache/pulsar-client-go/pulsar/internal/batch_builder.go
```

### CODE REVIEW

**Comment by sijie** [comment]
> To solve the conflict problem of zstd, the following files have been modified:

@tuteng Can you work with @wolfstudy to fix the issues in apache/pulsar-client-go repo?

**Comment by sijie** [comment]
@tuteng it seems that this pull request changes 41520 files. that doesn't seem to be possible to review the changes. Can you break down the pull request into multiple smaller pull requests?

**Comment by tuteng** [comment]
> @tuteng it seems that this pull request changes 41520 files. that doesn't seem to be possible to review the changes. Can you break down the pull request into multiple smaller pull requests?

Oh, oh, most of the files are from the third-party repository, because many files cannot be pulled down, so glide is still used to put the libraries together directly, resulting in a large repository.

image

I have tried several package managers to go, but there is still no better way. Many very basic packages cannot be pulled down, such as golang/x/net, golang/x/time, etc.

**Comment by sijie** [comment]
@tuteng can you put the vendor changes in one pull request and other changes in another pull request?

**Comment by tuteng** [comment]
> @tuteng can you put the vendor changes in one pull request and other changes in another pull request?

ok

**Comment by tuteng** [comment]
This task will be completed in two parts.
https://github.com/streamnative/pulsar-beat-output/pull/12
https://github.com/streamnative/pulsar-beat-output/pull/13

**Pull request closed without merging**
