### PR TITLE
chore: upgrade dependency

### PR DESCRIPTION
**Pull request by xuthus5**
update dependencies make pulsar-beat-output to support more beat and pulsar-client features.

### CODE REVIEW

**Review by hezhangjian — COMMENTED** [review]
do we really need go1.21? I would prefer choose max of `pulsar-client-go` and `beats`

**Comment by xuthus5** [comment]
> do we really need go1.21? I would prefer choose max of `pulsar-client-go` and `beats`

[Beats 7.17.21](https://github.com/elastic/beats/blob/v7.17.21/go.mod) minimum Go dependency version is 1.21

https://github.com/elastic/beats/blob/ba1f1c115316c2434bb0d713bc211d63bc899a14/go.mod#L3

**Review by hezhangjian — DISMISSED** [review]

**Comment by xuthus5** [comment]
@tuteng plz review.

**Review by tuteng — DISMISSED** [review]

**Comment by xuthus5** [comment]
update the version of goreleaser workflow at the same time.

**Review by tuteng — DISMISSED** [review]

**Comment by tuteng** [comment]
Thanks for your contribution @xuthus5 , there doesn't seem to be anything to check and I'm not sure why it's blocked, I'll find time to check it this week @xuthus5 @shoothzj

**Review by tuteng — APPROVED** [review]

**Review by hezhangjian — APPROVED** [review]

**Review by hezhangjian — APPROVED** [review]

**Pull request merged**
